---
dist: "xenial"
language: "python"

before_install:
    - pip install -U pip
    - pip install -U python-coveralls tox-travis

install:
    - pip install -e .

after_success:
    - coveralls

python:
    - 3.6
    - 3.7

script:
    - tox

deploy:
    provider: "pypi"
    distributions: "sdist bdist_wheel"
    user: "cerberus1746"
    skip_existing: true
    on:
        tags: true
